<span ng-if="editPerm" ng-show="textShow" text-spec-bind="currentText"></span>
<span ng-if="editPerm" ng-show="equationShow" eq-spec-bind="currentEquation"></span>
<span ng-if="editPerm" ng-show="symbolicShow" sym-spec-bind="currentSymbolic"></span>
<span ng-if="editPerm" ng-show="tableShow" table-spec-bind="currentTable"></span>
<span ng-if="editPerm" ng-show="loopShow" loop-spec-bind="currentLoop"></span>
<span ng-if="editPerm" ng-show="statementShow" statement-spec-bind="currentStatement"></span>
<span ng-if="editPerm" ng-show="plotShow" plot-spec-bind="currentPlot"></span>
<span ng-if="editPerm" ng-show="surfaceShow" surf-spec-bind="currentPlot"></span>
<span ng-if="editPerm" ng-show="imageShow" image-spec-bind="currentImage"></span>
<span ng-if="editPerm" ng-show="videoShow" video-spec-bind="currentVideo"></span>